# Placeholders:
# {message} - the chat message
# {name} - the player's name
# {displayname} - the player's display name / nickname
# {world} - the world name of the player's current world
# {prefix} - the player's highest priority prefix
# {suffix} - the player's highest priority suffix
# {prefixes} - the player's prefixes sorted by the highest priority
# {suffixes} - the player's suffixes sorted by the highest priority
# {username-color} - the player's or the group's username color
# {message-color} - the player's or the group's message color
chat-format: "{prefix}{name}&r: {message}"

group-formats:
#  default: "[default] {name}&r: {message}"
#  admin: "[admin] {name}&r: {message}"

# LuckMC Chat Settings
global-prefix: "&a[{world}]" # When string starts with !! sends the message to all players.
world-prefix: "&a[G]" # When string stars with ! sends the message to all players in the same world
radius-prefix: "" # When the string starts with nothing sends the message to players in 100 block radius
