name: LuckCore
version: '${project.version}'
main: net.luckmc.core.Main
authors: [wikmor, itscactus]
api-version: '1.13'
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  luckcore:
    description: Reload the configuration.
    permission: luckcore.reload
    usage: "Usage: /luckcore reload"